version: '3.5'
services:
  api:
    build:
      context: .
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    ports:
      - "8000:8000"